name: SonarQube Scan and Auto Merge PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write
  contents: write

jobs:
  # Job for SonarQube scan
  sonarqube-scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=sonar
            -Dsonar.projectName="Sonar Samples"
            -Dsonar.projectVersion=1.0
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

      - name: Fetch SonarQube Metrics
        id: fetch-metrics
        run: |
          PROJECT_KEY="sonar"
          RETRY_COUNT=0
          MAX_RETRIES=5

          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            echo "Attempt $((RETRY_COUNT+1)) to fetch metrics..."
            
            QUALITY_GATE_STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
              "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=$PROJECT_KEY" | \
              jq -r '.projectStatus.status // "ERROR"')

            METRICS_RESPONSE=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
              "${{ secrets.SONAR_HOST_URL }}/api/measures/component?component=$PROJECT_KEY&metricKeys=coverage,duplicated_lines_density,bugs,vulnerabilities,code_smells")

            if echo "$METRICS_RESPONSE" | jq -e '.errors' > /dev/null; then
              echo "Error fetching SonarQube metrics. Retrying..."
              RETRY_COUNT=$((RETRY_COUNT+1))
              sleep 10
              continue
            fi
            
            COVERAGE=$(echo "$METRICS_RESPONSE" | jq -r '.component.measures[]? | select(.metric == "coverage").value? // "0"')
            DUPLICATION=$(echo "$METRICS_RESPONSE" | jq -r '.component.measures[]? | select(.metric == "duplicated_lines_density").value? // "0"')
            BUGS=$(echo "$METRICS_RESPONSE" | jq -r '.component.measures[]? | select(.metric == "bugs").value? // "0"')
            VULNERABILITIES=$(echo "$METRICS_RESPONSE" | jq -r '.component.measures[]? | select(.metric == "vulnerabilities").value? // "0"')
            CODE_SMELLS=$(echo "$METRICS_RESPONSE" | jq -r '.component.measures[]? | select(.metric == "code_smells").value? // "0"')

            if [ -n "$COVERAGE" ] && [ -n "$QUALITY_GATE_STATUS" ]; then
              break
            else
              RETRY_COUNT=$((RETRY_COUNT+1))
              sleep 10
            fi
          done

          if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
            echo "Failed to fetch metrics after $MAX_RETRIES attempts"
            COVERAGE="0"
            QUALITY_GATE_STATUS="ERROR"
          fi

          echo "quality_passed=$( [ "$QUALITY_GATE_STATUS" = "OK" ] && echo "true" || echo "false" )" >> $GITHUB_OUTPUT
          echo "quality_status=$QUALITY_GATE_STATUS" >> $GITHUB_OUTPUT
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT

  auto-merge:
    name: Auto Merge PR
    runs-on: ubuntu-latest
    needs: sonarqube-scan
    if: needs.sonarqube-scan.outputs.quality_passed == 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Display Quality Status
        run: |
          echo "SonarQube Quality Status: ${{ needs.sonarqube-scan.outputs.quality_status }}"
          echo "Coverage: ${{ needs.sonarqube-scan.outputs.coverage }}%"

      - name: Auto Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          gh pr merge $PR_NUMBER --auto --squash
          echo "PR #$PR_NUMBER merged successfully!"

  quality-report:
    name: Quality Report
    runs-on: ubuntu-latest
    needs: sonarqube-scan
    if: always()
    steps:
      - name: Display Quality Status
        run: |
          echo "### SonarQube Quality Report" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Quality Gate Status | ${{ needs.sonarqube-scan.outputs.quality_status }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Code Coverage | ${{ needs.sonarqube-scan.outputs.coverage }}% |" >> $GITHUB_STEP_SUMMARY
